### ISSUE TITLE
unexpected '}'

### ISSUE THREAD

**Issue by Mnogous** [malashin/hoi4treesnap#6]
Issue with the Equestria at War mod, then looking at the 'eaw_goals.gfx' file.
![image](https://user-images.githubusercontent.com/90348655/182611098-f80bdb72-7240-497b-b7b2-2e26cf93b987.png)
![image](https://user-images.githubusercontent.com/90348655/182611145-53914f0e-df18-4540-80ec-84831996edda.png)

**Comment by malashin** [comment]
Fixed in https://github.com/malashin/hoi4treesnap/releases/tag/v0.5.11

Parser expected text after `#` symbol previously, not just newline.

```
SpriteType = {
	name = "GFX_goal_TBK_Union_Of_Wallnut_And_Dusk"
	texturefile = "gfx/interface/goals/TBK/TBK_Union_Of_Wallnut_And_Dusk.tga"
}
#
SpriteType = {
	name = "GFX_goal_CVA_blacklist"
	texturefile = "gfx/interface/goals/CVA/goal_CVA_blacklist.tga"
}
```
